### ISSUE TITLE
Return 500 error instead 404 in case config errors

### ISSUE THREAD

**Issue by badmansan** [jmartin82/mmock#134]
Hi there. Today I try to use mmoke first time. All going ok with first file. But my second file seems to be ignored, I get 404:
```
description: Use this for test if mock works
request:
    method: GET
    path: /test

response:
    statusCode: 200,
    body: I'm here!
```
Yes, I know - the comma after 200 must be deleted. All because the file was originally in json format, then I transform it to yaml & forgot to remove one comma. But can't see that mistake for a hour :smiling_face_with_tear: 

Maybe better to return error with message `file xxx can't be processed due to syntax error(s)`? Or, as another (may be better) solution, add one more tab in web interface with accepted & ignored files.

PS. I used docker image, not the command line tool.

**Comment by jmartin82** [comment]
Hey, thanks for reporting it.

It can not be converted to 500, because the error processing makes it impossible to know the original URL. The only solution could be to show the error processing configurations in the web interface, good idea. Now the only way is to check the output of the docker log to catch those errors.

I will have in mind this improvement.
