### ISSUE TITLE
Disable default stat collection. Update README.

### ISSUE THREAD

**Issue by pshirali** [jmartin82/mmock#78]
I noticed the CLI switch `-server-statistics` having a default value `true`. Though you are collecting anonymous stats, its a _dark pattern_ to leave this switch enabled by default.

Any privacy concerned user will definitely be caught by surprise.
1. There is no prominent mention in the README that stats are collected by `mmock` by default. Though there is a mention of statistics in the `Contributors` it doesn't convey that the tool collects anonymous stats.
2. The CLI switches listed in the README don't feature this flag (perhaps not updated). I happened to find this switch only after running the tool with `-h`; after which I began to inspect rest of the code.

I know this is a very subjective issue. You are entitled to your PoV. But, my request to you is:
1. Please disable this switch by default.
1. Please display information in a very prominent location in the README about mmock's statistic collection, the actual data collected and what can the user do to enable/disable it.

Please let me know your views. Please also let me know if you'd like a PR for this change. TIA.

**Comment by jmartin82** [comment]
Hi there, 

I've never been really concerned about this topic since you can disable the anonymous statics with a flag and you have all the code available to check how mmock is using them (mainly to check if the features are being used or not). 

But I see your point.

I will apply the following changes:

1. Update the readme adding all the flags from the CLI.
2. Add specific section about what data is collected by mmock and why
3. Add a line (if it's enabled) below the application banner explaining that mmock is sending statistic information and how to disable it.

Cheers

**Comment by dgellow** [comment]
I understand that you want usage statistics, but shouldn't the default be to not enable this feature instead? Such kind of metrics collection will be problematic in a lot of work places and is an unexpected default to have IMHO, personally I would expect something like this to be an opt-in feature instead of an opt-out.

**Comment by jmartin82** [comment]
For me with that is pretty clear what is mmock doing with the statistics, and how to disable it.

https://github.com/jmartin82/mmock/commit/f9c3570216aa5c9f3d400838030854066d7aa464

And I don't expect anybody concerned about this innocuous metrics.

Thanks!
